language: node_js

before_script:
  - npm install -g gatsby-cli

  node_js:
  - "stable"
  - "lts/*"

notifications:
  email:
    recipients:
      - shreyas.charming@gmail.com
    on_success: always
    on_failure: always

cache:
  directories:
    - ~/.npm
git:
  depth: 3

# script:
#   - gatsby build

deploy:
  provider: script
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  verbose: true
  script: npm install && npm run deploy
  on:
    branch: develop
