language: node_js

node_js:
  - "stable"
  - "lts/*"

notifications:
  email:
    recipients:
      - shreyas.charming@gmail.com
    on_success: always
    on_failure: always

cache:
  directories:
    - ~/.npm
git:
  depth: 3

script:
  - npm build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: develop
